In [418]:
import pandas as pd
import numpy as np

In [419]:
df=pd.read_csv("skincare_marketing_campaigns.csv")

In [420]:
#understanding the datq

In [421]:
df.head()

,campaign_id,campaign_name,campaign_type,target_audience,channel,date,spend,views,clicks,conversions,revenue
0,DBB_2025,Don't Burn for Beauty,Social Impact,Young Adults,Instagram,2025-07-02,10099.12,511560.0,42764.0,2227.0,98061.40
1,SS_2025,Summer Sale,Seasonal Sale,Adults,Facebook,2025-07-23,3478.75,34019.0,1769.0,305.0,14921.06
2,NF_2025,Nature First,Brand Image,Parents,Facebook,2025-03-16,5200.68,76079.0,2746.0,45.0,2374.23
3,AAR_2025,Anti-Aging Routine,Product Education,Seniors,Facebook,2025-01-12,2112.13,10050.0,337.0,210.0,31190.57
4,SS_2025,Summer Sale,Seasonal Sale,Adults,Email,2025-06-26,8966.25,42460.0,2070.0,198.0,10005.71

In [422]:
df['campaign_name']=df['campaign_name'].str.strip()

In [423]:
df['campaign_name'].unique()

array(["Don't Burn for Beauty", 'Summer Sale', 'Nature First',
       'Anti-Aging Routine', 'Product Launch', 'TikTok Skin Fails',
       'Holiday Prep', 'Skin Cancer Awareness', 'Black Friday'],
      dtype=object)

In [424]:
df['campaign_id'].unique()

array(['DBB_2025', 'SS_2025', 'NF_2025', 'AAR_2025', 'PL_2025',
       'TSF_2025', 'HP_2025', 'SCA_2025', 'BF_2025', ' NF_2025',
       'SS_2025 ', ' SCA_2025', ' TSF_2025', ' AAR_2025', 'DBB_2025 ',
       'HP_2025 ', 'NF_2025 ', 'PL_2025 ', 'AAR_2025 ', 'TSF_2025 ',
       ' PL_2025', 'SCA_2025 ', ' HP_2025', ' DBB_2025', ' BF_2025',
       'BF_2025 ', ' SS_2025'], dtype=object)

In [425]:
df['campaign_id']=df['campaign_id'].str.strip()

In [426]:
df['campaign_id'].unique()

array(['DBB_2025', 'SS_2025', 'NF_2025', 'AAR_2025', 'PL_2025',
       'TSF_2025', 'HP_2025', 'SCA_2025', 'BF_2025'], dtype=object)

In [427]:
df['target_audience']=df['target_audience'].str.strip()

In [428]:
df['target_audience'].unique()

array(['Young Adults', 'Adults', 'Parents', 'Seniors', 'Gen Z'],
      dtype=object)

In [429]:
df['channel']=df['channel'].str.strip()

In [430]:
df['channel'].unique()

array(['Instagram', 'Facebook', 'Email', 'LinkedIn', 'TikTok', 'YouTube',
       'youtube', 'email', 'instagram', 'facebook', 'linkedin', 'tiktok'],
      dtype=object)

In [431]:
df['channel']=df['channel'].str.lower()

In [432]:
df['channel'].unique()

array(['instagram', 'facebook', 'email', 'linkedin', 'tiktok', 'youtube'],
      dtype=object)

In [433]:
df.tail(100)

,campaign_id,campaign_name,campaign_type,target_audience,channel,date,spend,views,clicks,conversions,revenue
5819,AAR_2025,Anti-Aging Routine,Product Education,Seniors,email,2025-03-29,4630.48,7718.0,210.0,76.0,7006.12
5820,PL_2025,Product Launch,Product Launch,Seniors,facebook,2025-03-20,13268.28,283964.0,6450.0,559.0,61925.46
5821,AAR_2025,Anti-Aging Routine,Product Education,Seniors,linkedin,2025-01-25,3831.96,26157.0,600.0,294.0,43796.04
5822,PL_2025,Product Launch,Product Launch,Young Adults,instagram,2025-03-12,6130.06,85046.0,2824.0,106.0,9070.79
5823,PL_2025,Product Launch,Product Launch,Adults,facebook,2025-01-31,15621.95,121911.0,4382.0,382.0,43505.86
...,...,...,...,...,...,...,...,...,...,...,...
5914,TSF_2025,TikTok Skin Fails,Trend Counter,Young Adults,facebook,2025-04-06,23658.98,1013899.0,36175.0,1386.0,27923.37
5915,AAR_2025,Anti-Aging Routine,Product Education,Seniors,facebook,2025-01-24,5711.51,19242.0,543.0,85.0,8690.35
5916,TSF_2025,TikTok Skin Fails,Trend Counter,Gen Z,tiktok,2025-04-05,5660.11,887787.0,21960.0,1468.0,18563.77
5917,PL_2025,Product Launch,Product Launch,Seniors,email,2025-03-28,14975.64,66091.0,5058.0,749.0,53981.02
5918,TSF_2025,TikTok Skin Fails,Trend Counter,Young Adults,youtube,03-29-2025,5297.57,601964.0,36390.0,1283.0,40845.17

In [434]:
df.tail()

,campaign_id,campaign_name,campaign_type,target_audience,channel,date,spend,views,clicks,conversions,revenue
5914,TSF_2025,TikTok Skin Fails,Trend Counter,Young Adults,facebook,2025-04-06,23658.98,1013899.0,36175.0,1386.0,27923.37
5915,AAR_2025,Anti-Aging Routine,Product Education,Seniors,facebook,2025-01-24,5711.51,19242.0,543.0,85.0,8690.35
5916,TSF_2025,TikTok Skin Fails,Trend Counter,Gen Z,tiktok,2025-04-05,5660.11,887787.0,21960.0,1468.0,18563.77
5917,PL_2025,Product Launch,Product Launch,Seniors,email,2025-03-28,14975.64,66091.0,5058.0,749.0,53981.02
5918,TSF_2025,TikTok Skin Fails,Trend Counter,Young Adults,youtube,03-29-2025,5297.57,601964.0,36390.0,1283.0,40845.17

In [435]:
#type conversion

In [436]:
patterns = (df['date'].str.replace(r"\d", "D", regex=True))
patterns.unique()

array(['DDDD-DD-DD', 'DDDD/DD/DD', 'DD-DD-DDDD', 'DD/DD/DDDD',
       'DD.DD.DDDD'], dtype=object)

In [437]:
df['date']=df['date'].str.replace(r"\D+", "-", regex=True)

In [438]:
# STEP 1: Identify all date patterns in the data
# Replace digits with 'D' to see structure (e.g., 'YYYY-MM-DD' → 'DDDD-DD-DD')
patterns = (df['date'].str.replace(r"\d", "D", regex=True))
patterns.unique()

array(['DDDD-DD-DD', 'DD-DD-DDDD'], dtype=object)

In [439]:
df.tail()

,campaign_id,campaign_name,campaign_type,target_audience,channel,date,spend,views,clicks,conversions,revenue
5914,TSF_2025,TikTok Skin Fails,Trend Counter,Young Adults,facebook,2025-04-06,23658.98,1013899.0,36175.0,1386.0,27923.37
5915,AAR_2025,Anti-Aging Routine,Product Education,Seniors,facebook,2025-01-24,5711.51,19242.0,543.0,85.0,8690.35
5916,TSF_2025,TikTok Skin Fails,Trend Counter,Gen Z,tiktok,2025-04-05,5660.11,887787.0,21960.0,1468.0,18563.77
5917,PL_2025,Product Launch,Product Launch,Seniors,email,2025-03-28,14975.64,66091.0,5058.0,749.0,53981.02
5918,TSF_2025,TikTok Skin Fails,Trend Counter,Young Adults,youtube,03-29-2025,5297.57,601964.0,36390.0,1283.0,40845.17

In [440]:
df.isna().sum()

campaign_id          0
campaign_name        0
campaign_type        0
target_audience      0
channel              0
date                 0
spend              104
views              122
clicks             150
conversions        184
revenue            183
dtype: int64

In [441]:
df['cleaned_date']=pd.to_datetime(df["date"],format="mixed",errors="coerce")

In [442]:
df['cleaned_date']

0      2025-07-02
1      2025-07-23
2      2025-03-16
3      2025-01-12
4      2025-06-26
          ...
5914   2025-04-06
5915   2025-01-24
5916   2025-04-05
5917   2025-03-28
5918   2025-03-29
Name: cleaned_date, Length: 5919, dtype: datetime64[ns]

In [443]:
df['cleaned_date'].isna().any()

np.False_

In [444]:
df['cleaned_date'].dt.year.max()

np.int32(2025)

In [445]:
df['cleaned_date'].dt.year.min()

np.int32(2025)

In [446]:
df['date']=df['cleaned_date']

In [447]:
df.drop('cleaned_date', axis=1, inplace=True)

In [448]:
df.duplicated().sum()

np.int64(31)

In [449]:
df[df.duplicated()]

,campaign_id,campaign_name,campaign_type,target_audience,channel,date,spend,views,clicks,conversions,revenue
1506,SS_2025,Summer Sale,Seasonal Sale,Young Adults,youtube,2025-06-04,6293.45,139266.0,6652.0,1654.0,63051.03
2340,AAR_2025,Anti-Aging Routine,Product Education,Seniors,facebook,2025-06-03,7241.97,23485.0,1130.0,226.0,27222.78
2624,BF_2025,Black Friday,Seasonal Sale,Gen Z,instagram,2025-12-01,23452.21,304466.0,18127.0,4140.0,NaN
2836,AAR_2025,Anti-Aging Routine,Product Education,Adults,email,2025-03-25,5286.95,19038.0,650.0,545.0,38711.38
2853,SS_2025,Summer Sale,Seasonal Sale,Gen Z,tiktok,2025-07-14,4839.01,163814.0,14422.0,455.0,16090.76
2860,PL_2025,Product Launch,Product Launch,Young Adults,tiktok,2025-03-10,31254.19,1451457.0,53768.0,0.0,0.00
2987,SS_2025,Summer Sale,Seasonal Sale,Young Adults,instagram,2025-07-27,2671.77,31008.0,1366.0,199.0,11821.37
3315,DBB_2025,Don't Burn for Beauty,Social Impact,Gen Z,instagram,2025-08-09,9696.13,412342.0,60340.0,3016.0,66371.53
3355,NF_2025,Nature First,Brand Image,Parents,email,2025-03-07,5633.37,24602.0,1848.0,121.0,8714.80
3914,AAR_2025,Anti-Aging Routine,Product Education,Young Adults,youtube,2025-01-29,8272.32,147153.0,4803.0,790.0,74341.82
4113,NF_2025,Nature First,Brand Image,Young Adults,instagram,2025-04-09,5911.64,49793.0,1494.0,18.0,1661.29
4157,SS_2025,Summer Sale,Seasonal Sale,Young Adults,facebook,2025-07-08,3685.53,97798.0,4941.0,565.0,30603.69
4192,NF_2025,Nature First,Brand Image,Parents,facebook,2025-04-25,3076.63,21653.0,993.0,14.0,832.83
4273,SS_2025,Summer Sale,Seasonal Sale,Adults,email,2025-05-17,4557.77,17595.0,1116.0,768.0,41357.85
4440,AAR_2025,Anti-Aging Routine,Product Education,Seniors,email,2025-06-01,4283.19,10575.0,802.0,629.0,71776.06
4509,SS_2025,Summer Sale,Seasonal Sale,Young Adults,email,2025-05-18,8572.17,106232.0,0.0,0.0,0.00
4762,NF_2025,Nature First,Brand Image,Parents,facebook,2025-04-29,5288.01,41057.0,0.0,0.0,0.00
5020,AAR_2025,Anti-Aging Routine,Product Education,Young Adults,facebook,2025-05-08,4305.75,73285.0,2140.0,351.0,21360.21
5261,AAR_2025,Anti-Aging Routine,Product Education,Seniors,facebook,2025-03-12,3067.12,NaN,NaN,122.0,14610.96
5317,SS_2025,Summer Sale,Seasonal Sale,Young Adults,facebook,2025-05-28,7621.27,167565.0,7547.0,1389.0,76746.74
5321,PL_2025,Product Launch,Product Launch,Seniors,email,2025-01-26,8001.32,33118.0,1449.0,164.0,19647.78
5349,AAR_2025,Anti-Aging Routine,Product Education,Adults,linkedin,2025-01-16,3950.48,10695.0,144.0,16.0,1804.16
5476,BF_2025,Black Friday,Seasonal Sale,Young Adults,tiktok,2025-12-04,21003.02,466883.0,17849.0,3924.0,264035.89
5481,NF_2025,Nature First,Brand Image,Gen Z,youtube,2025-04-06,5938.60,217721.0,3877.0,86.0,4194.46
5529,AAR_2025,Anti-Aging Routine,Product Education,Seniors,linkedin,2025-04-16,4692.37,17132.0,458.0,96.0,8517.69
5594,NF_2025,Nature First,Brand Image,Parents,instagram,2025-03-24,5612.78,41058.0,1183.0,24.0,1406.48
5708,AAR_2025,Anti-Aging Routine,Product Education,Young Adults,facebook,2025-05-05,4006.33,30658.0,685.0,154.0,11264.15
5789,SS_2025,Summer Sale,Seasonal Sale,Young Adults,facebook,2025-07-16,1615.00,23629.0,1208.0,72.0,3323.60
5823,PL_2025,Product Launch,Product Launch,Adults,facebook,2025-01-31,15621.95,121911.0,4382.0,382.0,43505.86
5888,DBB_2025,Don't Burn for Beauty,Social Impact,Adults,facebook,2025-08-03,4242.88,70638.0,4913.0,189.0,8462.57
5891,AAR_2025,Anti-Aging Routine,Product Education,Seniors,linkedin,2025-02-27,2965.86,8425.0,155.0,58.0,5884.77

In [450]:
df = df.drop_duplicates()

In [451]:
df['spend'].isna().sum()

np.int64(104)

In [452]:
df[df['spend'].isna()]

,campaign_id,campaign_name,campaign_type,target_audience,channel,date,spend,views,clicks,conversions,revenue
23,AAR_2025,Anti-Aging Routine,Product Education,Young Adults,email,2025-03-09,NaN,17203.0,1224.0,203.0,NaN
43,HP_2025,Holiday Prep,Seasonal Education,Adults,email,2025-10-27,NaN,34180.0,3341.0,771.0,40839.82
168,DBB_2025,Don't Burn for Beauty,Social Impact,Young Adults,instagram,2025-07-10,NaN,218857.0,8642.0,197.0,8316.37
198,NF_2025,Nature First,Brand Image,Gen Z,youtube,2025-03-22,NaN,352032.0,14259.0,NaN,39943.64
279,SS_2025,Summer Sale,Seasonal Sale,Young Adults,youtube,2025-05-27,NaN,26198.0,1471.0,54.0,3836.31
...,...,...,...,...,...,...,...,...,...,...,...
5677,AAR_2025,Anti-Aging Routine,Product Education,Adults,linkedin,2025-03-25,NaN,22717.0,1277.0,373.0,33295.92
5692,PL_2025,Product Launch,Product Launch,Young Adults,youtube,2025-02-20,NaN,602335.0,21280.0,1429.0,133389.22
5704,SS_2025,Summer Sale,Seasonal Sale,Parents,facebook,2025-07-20,NaN,31148.0,1445.0,NaN,3252.33
5809,PL_2025,Product Launch,Product Launch,Young Adults,instagram,2025-03-17,NaN,1349915.0,71547.0,2141.0,220060.75
5841,TSF_2025,TikTok Skin Fails,Trend Counter,Young Adults,facebook,2025-03-27,NaN,723990.0,41655.0,3165.0,106730.52

In [453]:
# Count missing 'spend' per category
df.groupby('campaign_name')['spend'].apply(lambda x: x.isna().sum())

campaign_name
Anti-Aging Routine       27
Black Friday              4
Don't Burn for Beauty     8
Holiday Prep              4
Nature First             18
Product Launch           14
Skin Cancer Awareness     4
Summer Sale              14
TikTok Skin Fails        11
Name: spend, dtype: int64

In [454]:
df.groupby('campaign_name').size()

campaign_name
Anti-Aging Routine       1487
Black Friday              262
Don't Burn for Beauty     478
Holiday Prep              256
Nature First              874
Product Launch            741
Skin Cancer Awareness     277
Summer Sale               908
TikTok Skin Fails         605
dtype: int64

In [455]:
df['spend'].describe()

count    5.784000e+03
mean     9.816529e+03
std      2.114325e+04
min      8.866300e+02
25%      4.181762e+03
50%      5.903145e+03
75%      9.672710e+03
max      1.064410e+06
Name: spend, dtype: float64

In [456]:
# Check if there are any negative numbers
(df['spend'] < 0).any()

np.False_

In [457]:
df.dtypes

campaign_id                object
campaign_name              object
campaign_type              object
target_audience            object
channel                    object
date               datetime64[ns]
spend                     float64
views                     float64
clicks                    float64
conversions               float64
revenue                   float64
dtype: object

In [458]:
(df["spend"] < 0).any()

np.False_

In [459]:
(df["views"] < 0).any()

np.False_

In [460]:
(df["clicks"] < 0).any()

np.False_

In [461]:
(df["conversions"] < 0).any()

np.False_

In [462]:
(df["revenue"] < 0).any()

np.False_

In [463]:
df.isna().mean() * 100

campaign_id        0.000000
campaign_name      0.000000
campaign_type      0.000000
target_audience    0.000000
channel            0.000000
date               0.000000
spend              1.766304
views              2.055027
clicks             2.530571
conversions        3.125000
revenue            3.091033
dtype: float64

In [464]:
# Check skew for all numeric columns
df.select_dtypes(include='number').skew()

spend          27.266310
views          19.777779
clicks         28.752501
conversions    43.832489
revenue        26.157062
dtype: float64

In [465]:
df[df["views"].isna()].describe()

,date,spend,views,clicks,conversions,revenue
count,121,119.00000,0.0,119.000000,117.000000,119.000000
mean,2025-05-06 09:55:02.479338752,9311.08605,NaN,26386.714286,932.811966,46063.276303
min,2025-01-25 00:00:00,1365.17000,NaN,0.000000,0.000000,0.000000
25%,2025-03-16 00:00:00,4262.77500,NaN,1216.500000,107.000000,6564.120000
50%,2025-04-30 00:00:00,6133.07000,NaN,4040.000000,279.000000,22785.750000
75%,2025-06-04 00:00:00,9079.15000,NaN,12126.000000,812.000000,48612.045000
max,2025-12-01 00:00:00,98380.03000,NaN,732694.000000,11862.000000,536934.250000
std,NaN,11229.08053,NaN,83534.148122,1840.262312,78099.394865

In [466]:
df[['spend','views']].corr() #both spend and views have NaNs so i can't fill views with spend , thats why i'm gonna fill views with campaign name and channel first

         spend    views
spend  1.00000  0.82799
views  0.82799  1.00000

In [467]:
df['views_was_missing'] = df['views'].isna()

df['views'] = df.groupby(['channel', 'campaign_name'])['views'].transform(lambda x: x.fillna(x.median()))

In [468]:
original = df[~df['views_was_missing']]['views']
imputed = df[df['views_was_missing']]['views']

print("Original median:", original.median())

Original median: 87419.0
Imputed median:  77922.0

In [469]:

df['spend_was_missing'] = df['spend'].isna()
df['spend'] = df.groupby(['channel', 'campaign_name'])['spend'] \
                .transform(lambda x: x.fillna(x.median()))
original = df[~df['spend_was_missing']]['spend']
imputed = df[df['spend_was_missing']]['spend']

Original median: 5903.145
Imputed median:  5922.655

In [470]:
#Spend missing values were imputed using the median per campaign and channel to preserve dataset completeness for analysis, because zero spend cannot be assumed. Revenue values were left as NaN because imputing them could introduce bias, so analysis on revenue was performed only on rows with actual recorded values.

In [471]:

df['conversions_was_missing'] = df['conversions'].isna()
df['conversions'] = df.groupby(['channel', 'campaign_name'])['conversions'] \
                .transform(lambda x: x.fillna(x.median()))
original = df[~df['conversions_was_missing']]['conversions']
imputed = df[df['conversions_was_missing']]['conversions']

Original median: 286.0
Imputed median:  259.0

In [472]:
df.isna().sum()

campaign_id                  0
campaign_name                0
campaign_type                0
target_audience              0
channel                      0
date                         0
spend                        0
views                        0
clicks                     149
conversions                  0
revenue                    182
views_was_missing            0
spend_was_missing            0
conversions_was_missing      0
dtype: int64

In [473]:
#Impressions → Clicks → Conversions → Revenue

In [474]:
df["rev_missing"] = df["clicks"].isna().astype(int)

channel_missing = (
    df.groupby("channel")["rev_missing"]
      .mean()
      .sort_values(ascending=False)
)

print(channel_missing)

channel
linkedin     0.040310
youtube      0.031678
instagram    0.023629
tiktok       0.022727
email        0.021978
facebook     0.017464
Name: rev_missing, dtype: float64

In [475]:
# Step 1: create missing flag BEFORE anything
df['clicks_missing'] = df['clicks'].isna()

# Step 2: fill missing clicks with channel + campaign median
df['clicks'] = df.groupby(['channel', 'campaign_name'])['clicks'] \
                 .transform(lambda x: x.fillna(x.median()))

# Step 3: enforce clicks = 0 where conversions = 0
df.loc[df["conversions"] == 0, "clicks"] = 0

# Step 4: recalc missing flag if you want to track imputed rows
df['clicks_imputed_flag'] = df['clicks_missing'] & (df["conversions"] != 0)

# Step 5: separate original vs imputed for median check
original = df.loc[~df['clicks_imputed_flag'], 'clicks']
imputed = df.loc[df['clicks_imputed_flag'], 'clicks']

Original median: 3562.0
Imputed median:  2570.0

In [476]:
import numpy as np

# Flag missing revenue
df['revenue_was_missing'] = df['revenue'].isna()

# Handle structural zeros
df.loc[df['conversions'] == 0, 'revenue'] = 0
df.loc[df['conversions'] == 0, 'revenue_was_missing'] = False  # <- fix dtype

# Compute RPC (Revenue per Click)
df['rpc'] = df['revenue'] / df['clicks'].replace(0, np.nan)
df['rpc'] = df.groupby(['channel','campaign_name'])['rpc'].transform(lambda x: x.fillna(x.median()))

# Impute missing revenue
df['revenue'] = df['revenue'].fillna((df['rpc'] * df['clicks']).round())
df['revenue'] = df['revenue'].clip(lower=0)

# Check medians
original_revenue = df[~df['revenue_was_missing']]['revenue']
imputed_revenue = df[df['revenue_was_missing']]['revenue']

Revenue - Original median: 18979.18
Revenue - Imputed median: 25237.5

In [477]:
df.to_csv("clean_marketing_data.csv", index=False)

In [478]:
df.dtypes

campaign_id                        object
campaign_name                      object
campaign_type                      object
target_audience                    object
channel                            object
date                       datetime64[ns]
spend                             float64
views                             float64
clicks                            float64
conversions                       float64
revenue                           float64
views_was_missing                    bool
spend_was_missing                    bool
conversions_was_missing              bool
rev_missing                         int64
clicks_missing                       bool
clicks_imputed_flag                  bool
revenue_was_missing                  bool
rpc                               float64
dtype: object